services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: project-name-img
    container_name: project-name-app
    restart: on-failure:3
    env_file:
      - .env.prod
    ports:
      - '3000:3000'
